### PR TITLE
Fix incorrect construction of magic command azure.quotas

### PR DESCRIPTION
**Pull request by ricardo-espinoza**
Quotas command was constructed using an incorrect name.

Updating to the intended name.

### CODE REVIEW

**Review by cgranade — APPROVED** [review]
It looks like the API documentation comment at L17 may also be good to update, but otherwise LGTM.

**Comment by ricardo-espinoza** [comment]
> It looks like the API documentation comment at L17 may also be good to update, but otherwise LGTM.

Thanks for the catch, @cgranade . To avoid delaying the pending PR we have tonight, I'll leave as is, but I'll correct the comment in the next few days.

**Comment by cgranade** [comment]
Force merging to restore build.

**Pull request merged**
