### PR TITLE
Workspace Loader Only Check Top Level Directory

### PR DESCRIPTION
**Pull request by ScottCarda-MS**
Changed the behavior of the workspace loader's file search to only check for qs file in the top level folder.

### CODE REVIEW

**Comment by ScottCarda-MS** [comment]
PR for issue #20.

**Comment by tcNickolas** [comment]
Would it be possible to get instructions on how to check that this change doesn't break the katas?

**Comment by cgranade** [comment]
> Would it be possible to get instructions on how to check that this change doesn't break the katas?

This change causes that, when called from IQ# or Python, all Q# code must be in the current working directory or in a referenced package. There should be an alpha package from this PR on the prerelease feed that will allow for testing, just need to make sure you have a NuGet.Config set up to point to that feed (this repo has an example of such a config in its root).

**Comment by anpaz-msft** [comment]
@tcNickolas , I took a quick look at Katas, and all the .qs files are in the same folder as the notebook, so it should not affect them.
There are a couple of other .qs files under the `$/utilities` folder, but should not be affected.

**Comment by ScottCarda-MS** [comment]
@tcNickolas mentioned that this may cause issues with the DeutschJozsaAlgorithm kata. I am at this time unable to test this change against that kata.

**Pull request merged**
