### PR TITLE
Remove Honeywell provider and update tests to use Quantinuum

### PR DESCRIPTION
**Pull request by vxfield**
### Context
In November 2021, Honeywell became Quantinuum: Press release: [Quantinuum is a result of the combination of two global leaders in quantum computing: Honeywell Quantum Solutions and Cambridge Quantum](https://www.quantinuum.com/pressrelease/introducing-quantinuum)

In February/March 2022, Azure Quantum started supporting the Quantinuum provider and targets.

### This PR
This PR removes the Honewell provider, targets and update tests to use Quantinuum provider.

### CODE REVIEW

**Review by anpaz — APPROVED** [review]
Can we run a full release and e2e tests on this before merging please?

**Review by cesarzc — APPROVED** [review]

**Comment by vxfield** [comment]
> Can we run a full release and e2e tests on this before merging please?

I ran a full release build (#0.26.236583) and E2E tests and they passed, so I'll merge this PR.

**Comment by vxfield** [comment]
There is a transient issue with DevSkim so I'm bypassing branch protections as all other requirements and tests passed.

**Pull request merged**
