### PR TITLE
Abstract ExecutionPathTracer into its own project

### PR DESCRIPTION
**Pull request by theRoughCode**
As part of future efforts to use the tracer in other projects, this PR takes the first step at decoupling `ExecutionPathTracer` from `IQSharp.Core` and moving it into its own project under the `ExecutionPathTracer` folder.

### CODE REVIEW

**Comment by cgranade** [comment]
As a quick note, the term "tracer" has often been used informally to refer to the trace simulator.

**Comment by rmshaffer** [comment]
> As a quick note, the term "tracer" has often been used informally to refer to the trace simulator.

Thanks @cgranade, I didn't realize that. Maybe then `TraceVisualizer` would be less ambiguous?

**Comment by theRoughCode** [comment]
@rmshaffer @cgranade I did consider that as well, and I'm open to suggestions! I thought of `TraceVisualizer` but this folder doesn't do any of the visualization, just traces out the operations into an intermediate representation to pass to the Visualizer (JS).

**Comment by rmshaffer** [comment]
> @rmshaffer Ryan Shaffer FTE @cgranade Chris Granade FTE I did consider that as well, and I'm open to suggestions! I thought of `TraceVisualizer` but this folder doesn't do any of the visualization, just traces out the operations into an intermediate representation to pass to the Visualizer (JS).

That's a good point as well. Going back to your original comment, I wonder why `ExecutionPathTracer` doesn't work? e.g. in `AzureClient` project, both the namespace and a public class within the namespace are called `AzureClient` and everything seems to work out.

**Comment by theRoughCode** [comment]
@rmshaffer I'll try it out again haha

**Comment by theRoughCode** [comment]
@rmshaffer ah, it might have been solved in `src\Kernel\Magic\Resolution\MagicResolver.cs` L45 with `AzureClient/AzureClient`.

**Pull request merged**
